In [2]:
import pandas as pd

df = pd.read_csv("merged_final.csv")
df['ENA_Accession'] = df['submitted_ftp'].str.extract(r'\/([^\/]+)\/[^\/]+\.cram')

                V1    cell_name  V1.1  assigned  auxDir  cell_filter  \
0       21241_6#10   21241_6#10     1  aux_info    True     0.999061
1      21241_6#100  21241_6#100     1  aux_info    True     0.998698
2      21241_6#101  21241_6#101     1  aux_info    True     0.998417
3      21241_6#103  21241_6#103     1  aux_info    True     0.998256
4      21241_6#104  21241_6#104     1  aux_info    True     0.998874
...            ...          ...   ...       ...     ...          ...
22110   25757_6#93   25757_6#93     1  aux_info    True     0.999754
22111   25757_6#94   25757_6#94     1  aux_info    True     0.999666
22112   25757_6#95   25757_6#95     1  aux_info    True     0.999782
22113   25757_6#98   25757_6#98     1  aux_info    True     0.999794
22114   25757_6#99   25757_6#99     1  aux_info    True     0.999760

      compatible_fragment_ratio   day donor expected_format  ...  \
0                          day3  fafq    IU         expt_10  ...
1                          day3  fafq    IU         expt_10  ...
2                          day3  wopl    IU         expt_10  ...
3                          day3  sebz    IU         expt_10  ...
4                          day3  hayt    IU         expt_10  ...
...                         ...   ...   ...             ...  ...
22110                      day2  hecn    IU         expt_45  ...
22111                      day2  tert    IU         expt_45  ...
22112                      day2  kuco    IU         expt_45  ...
22113                      day2  tert    IU         expt_45  ...
22114                      day2  tert    IU         expt_45  ...

       PC1_top500hvgs  PC1_top1000hvgs  PC1_top2000hvgs  princ_curve  \
0           32.193582        36.657563        39.913409    86.555089
1           29.271910        35.509619        42.029886    84.716979
2           30.458309        35.879669        42.395477    90.598849
3           31.063225        37.679783        44.919726    96.535839
4           36.168878        41.733983        46.977869    91.871721
...               ...              ...              ...          ...
22110       28.451680        33.644807        36.639880    86.356704
22111       30.489584        36.429202        42.885288    90.445457
22112       24.932563        29.376279        33.083839    84.417981
22113       21.478714        24.690528        25.464886    80.766480
22114       25.335769        27.799068        29.686716    81.630213

       princ_curve_scaled01 study_accession sample_accession  \
0                  0.763442      PRJEB14362     SAMEA4494285
1                  0.747229      PRJEB14362     SAMEA4494856
2                  0.799109      PRJEB14362     SAMEA4494857
3                  0.851475      PRJEB14362     SAMEA4494859
4                  0.810336      PRJEB14362     SAMEA4494860
...                     ...             ...              ...
22110              0.761692      PRJEB14362     SAMEA3753549
22111              0.797756      PRJEB14362     SAMEA3753550
22112              0.744592      PRJEB14362     SAMEA3753551
22113              0.712384      PRJEB14362     SAMEA3753554
22114              0.720003      PRJEB14362     SAMEA3753555

                                           submitted_ftp  \
0      ftp.sra.ebi.ac.uk/vol1/run/ERR173/ERR1737560/2...
1      ftp.sra.ebi.ac.uk/vol1/run/ERR173/ERR1737650/2...
2      ftp.sra.ebi.ac.uk/vol1/run/ERR173/ERR1737651/2...
3      ftp.sra.ebi.ac.uk/vol1/run/ERR173/ERR1737653/2...
4      ftp.sra.ebi.ac.uk/vol1/run/ERR173/ERR1737654/2...
...                                                  ...
22110  ftp.sra.ebi.ac.uk/vol1/run/ERR297/ERR2976442/2...
22111  ftp.sra.ebi.ac.uk/vol1/run/ERR297/ERR2976443/2...
22112  ftp.sra.ebi.ac.uk/vol1/run/ERR297/ERR2976444/2...
22113  ftp.sra.ebi.ac.uk/vol1/run/ERR297/ERR2976447/2...
22114  ftp.sra.ebi.ac.uk/vol1/run/ERR297/ERR2976448/2...

                                               fastq_ftp  ENA_Accession
0      ftp.sra.ebi.ac.uk/vol1/fastq/ERR173/000/ERR173...     ERR1737560
1      ftp.sra.ebi.ac.uk/vol1/fastq/ERR173/000/ERR173...     ERR1737650
2      ftp.sra.ebi.ac.uk/vol1/fastq/ERR173/001/ERR173...     ERR1737651
3      ftp.sra.ebi.ac.uk/vol1/fastq/ERR173/003/ERR173...     ERR1737653
4      ftp.sra.ebi.ac.uk/vol1/fastq/ERR173/004/ERR173...     ERR1737654
...                                                  ...            ...
22110  ftp.sra.ebi.ac.uk/vol1/fastq/ERR297/002/ERR297...     ERR2976442
22111  ftp.sra.ebi.ac.uk/vol1/fastq/ERR297/003/ERR297...     ERR2976443
22112  ftp.sra.ebi.ac.uk/vol1/fastq/ERR297/004/ERR297...     ERR2976444
22113  ftp.sra.ebi.ac.uk/vol1/fastq/ERR297/007/ERR297...     ERR2976447
22114  ftp.sra.ebi.ac.uk/vol1/fastq/ERR297/008/ERR297...     ERR2976448

[22115 rows x 100 columns]

In [3]:
df.head(5)

,V1,cell_name,V1.1,assigned,auxDir,cell_filter,compatible_fragment_ratio,day,donor,expected_format,...,PC1_top500hvgs,PC1_top1000hvgs,PC1_top2000hvgs,princ_curve,princ_curve_scaled01,study_accession,sample_accession,submitted_ftp,fastq_ftp,ENA_Accession
0,21241_6#10,21241_6#10,1,aux_info,True,0.999061,day3,fafq,IU,expt_10,...,32.193582,36.657563,39.913409,86.555089,0.763442,PRJEB14362,SAMEA4494285,ftp.sra.ebi.ac.uk/vol1/run/ERR173/ERR1737560/2...,ftp.sra.ebi.ac.uk/vol1/fastq/ERR173/000/ERR173...,ERR1737560
1,21241_6#100,21241_6#100,1,aux_info,True,0.998698,day3,fafq,IU,expt_10,...,29.271910,35.509619,42.029886,84.716979,0.747229,PRJEB14362,SAMEA4494856,ftp.sra.ebi.ac.uk/vol1/run/ERR173/ERR1737650/2...,ftp.sra.ebi.ac.uk/vol1/fastq/ERR173/000/ERR173...,ERR1737650
2,21241_6#101,21241_6#101,1,aux_info,True,0.998417,day3,wopl,IU,expt_10,...,30.458309,35.879669,42.395477,90.598849,0.799109,PRJEB14362,SAMEA4494857,ftp.sra.ebi.ac.uk/vol1/run/ERR173/ERR1737651/2...,ftp.sra.ebi.ac.uk/vol1/fastq/ERR173/001/ERR173...,ERR1737651
3,21241_6#103,21241_6#103,1,aux_info,True,0.998256,day3,sebz,IU,expt_10,...,31.063225,37.679783,44.919726,96.535839,0.851475,PRJEB14362,SAMEA4494859,ftp.sra.ebi.ac.uk/vol1/run/ERR173/ERR1737653/2...,ftp.sra.ebi.ac.uk/vol1/fastq/ERR173/003/ERR173...,ERR1737653
4,21241_6#104,21241_6#104,1,aux_info,True,0.998874,day3,hayt,IU,expt_10,...,36.168878,41.733983,46.977869,91.871721,0.810336,PRJEB14362,SAMEA4494860,ftp.sra.ebi.ac.uk/vol1/run/ERR173/ERR1737654/2...,ftp.sra.ebi.ac.uk/vol1/fastq/ERR173/004/ERR173...,ERR1737654

In [6]:
columns_of_interest = ['cell_name', 'donor_short_id', 'donor_long_id', 'study_accession', 'sample_accession', 'ENA_Accession']
df_final = df[columns_of_interest]
df_final.head(5)

,cell_name,donor_short_id,donor_long_id,study_accession,sample_accession,ENA_Accession
0,21241_6#10,fafq_1,HPSI0314i-fafq_1,PRJEB14362,SAMEA4494285,ERR1737560
1,21241_6#100,fafq_1,HPSI0314i-fafq_1,PRJEB14362,SAMEA4494856,ERR1737650
2,21241_6#101,wopl_1,HPSI1013i-wopl_1,PRJEB14362,SAMEA4494857,ERR1737651
3,21241_6#103,sebz_1,HPSI1013i-sebz_1,PRJEB14362,SAMEA4494859,ERR1737653
4,21241_6#104,hayt_1,HPSI1113i-hayt_1,PRJEB14362,SAMEA4494860,ERR1737654

In [7]:
df_final.to_csv('merged_final_with_ENA.csv', index = False)